### ISSUE TITLE
Improvement - partial import of react-bootstrap

### ISSUE THREAD

**Issue by avnersorek** [asadm/react-hints#1]
Hi 

Great library, thanks for making it!

I see you are importing entire react-bootstrap, a little too much if my application does not use bootstrap.
WDYT about making a partial import for the bootstrap components?
See 'bundle size optimisation' in https://react-bootstrap.github.io/getting-started/introduction#commonjs

If that works for you, I will be glad to open a PR for it.

Thanks!

**Comment by asadm** [comment]
Hello, 

That sounds great to me. PR is most welcome!

**Comment by avnersorek** [comment]
PR opened.
``dist`` size for this repo decreased by about 1 Mb
Thanks

**Comment by asadm** [comment]
Awesome!

**Comment by avnersorek** [comment]
Thank you!
Could you publish to NPM ?
Thanks

**Comment by asadm** [comment]
Ah! I have pushed the [update](https://www.npmjs.com/package/react-hints/v/0.1.2).
